### PR TITLE
Merge it!

### PR DESCRIPTION
**Pull request by bakercp**

### CODE REVIEW

**Comment by bakercp** [comment]
@armadillu Any reason I shouldn't merge this back into the master?  Looks good to me.

**Comment by armadillu** [comment]
Yeah I vaguely remember there was a reason I didn't PR. I think it broke some of your functionality, but can't remember 100%; let me have a look

**Comment by armadillu** [comment]
I can't seem to find it now; I think the problem was that I never got to play with the Utils themselves, I only cared about the packer... So I was unsure if changing the packer would break the utils.

**Comment by bakercp** [comment]
nice.  I'll take a look and merge it.  from what i saw, i didn't see any
breaking changes.  glad you've found it useful!


---
http://christopherbaker.net

**Comment by armadillu** [comment]
I just found the issue; for some reason it is not stable over time. And yeah it's super useful thx for sharing!

**Comment by bakercp** [comment]
which part was not stable?


---
http://christopherbaker.net

**Comment by armadillu** [comment]
Yeah when padding is 0 it is stable; when its's > 0 it seems to find different valid solutions over different frames. You can see it by running the "example_simple_packing"

**Comment by armadillu** [comment]
http://youtu.be/19ccnrTszq8

**Comment by armadillu** [comment]
I couldn't really figure it out, but as I needed a single-time solution; if worked ok for me... But you probably want a system that gets you the same result every time you run it, that's why I never made a PR.

**Comment by bakercp** [comment]
Interesting -- I built the code for creating texture atlases for the forever in development ofFont and I think I may have added a padding feature ... I'll dig that up and compare notes sometime soon.

**Comment by bakercp** [comment]
Also -- the video is private.  Any chance of making it public it?

**Comment by armadillu** [comment]
public now!

**Comment by armadillu** [comment]
ofGetMouseX() is mapped to the amount of padding... as you can see, it gets jumpy when there's any padding at all.

**Comment by bakercp** [comment]
Thanks!  Sorry this took so long ...

**Comment by armadillu** [comment]
Hey! I still haven't figured out why its leads to non-identical results with the same input; just want to make sure you are aware of that. This may be a show stopper for some cases.

**Comment by bakercp** [comment]
Strange.  Rounding errors caused by neutrinos?  :) I'll keep an eye open.

**Pull request merged**
